  CREATE TABLE "MARCO"."PRODUCTS" 
   (	"ID_PRODUCT" NUMBER(4,0) NOT NULL ENABLE, 
	"NAME_PRODUCT" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"CODE_PRODUCT" NUMBER(38,0) NOT NULL ENABLE, 
	"FK_SHOP" NUMBER(4,0), 
	 PRIMARY KEY ("ID_PRODUCT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SHOP" FOREIGN KEY ("FK_SHOP")
	  REFERENCES "MARCO"."SHOPS" ("ID_SHOP") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;